
package com.hundsun.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FundQueryService", targetNamespace = "http://service.hundsun.com", wsdlLocation = "file:/D:/webService/fundquery.xml")
public class FundQueryService
    extends Service
{

    private final static URL FUNDQUERYSERVICE_WSDL_LOCATION;
    private final static WebServiceException FUNDQUERYSERVICE_EXCEPTION;
    private final static QName FUNDQUERYSERVICE_QNAME = new QName("http://service.hundsun.com", "FundQueryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/webService/fundquery.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUNDQUERYSERVICE_WSDL_LOCATION = url;
        FUNDQUERYSERVICE_EXCEPTION = e;
    }

    public FundQueryService() {
        super(__getWsdlLocation(), FUNDQUERYSERVICE_QNAME);
    }

    public FundQueryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FUNDQUERYSERVICE_QNAME, features);
    }

    public FundQueryService(URL wsdlLocation) {
        super(wsdlLocation, FUNDQUERYSERVICE_QNAME);
    }

    public FundQueryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FUNDQUERYSERVICE_QNAME, features);
    }

    public FundQueryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FundQueryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FundQueryServicePortType
     */
    @WebEndpoint(name = "FundQueryServiceHttpPort")
    public FundQueryServicePortType getFundQueryServiceHttpPort() {
        return super.getPort(new QName("http://service.hundsun.com", "FundQueryServiceHttpPort"), FundQueryServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FundQueryServicePortType
     */
    @WebEndpoint(name = "FundQueryServiceHttpPort")
    public FundQueryServicePortType getFundQueryServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.hundsun.com", "FundQueryServiceHttpPort"), FundQueryServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUNDQUERYSERVICE_EXCEPTION!= null) {
            throw FUNDQUERYSERVICE_EXCEPTION;
        }
        return FUNDQUERYSERVICE_WSDL_LOCATION;
    }

}
