
package com.hundsun.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.hundsun.dto.QueryPayRequest;
import com.hundsun.dto.QueryPayResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FundQueryServicePortType", targetNamespace = "http://service.hundsun.com")
@XmlSeeAlso({
    com.hundsun.dto.ObjectFactory.class,
    com.hundsun.service.ObjectFactory.class
})
public interface FundQueryServicePortType {


    /**
     * 
     * @param in0
     * @return
     *     returns com.hundsun.dto.QueryPayResponse
     */
    @WebMethod(operationName = "QueryPay")
    @WebResult(name = "out", targetNamespace = "http://service.hundsun.com")
    @RequestWrapper(localName = "QueryPay", targetNamespace = "http://service.hundsun.com", className = "com.hundsun.service.QueryPay")
    @ResponseWrapper(localName = "QueryPayResponse", targetNamespace = "http://service.hundsun.com", className = "com.hundsun.service.QueryPayResponse")
    public QueryPayResponse queryPay(
        @WebParam(name = "in0", targetNamespace = "http://service.hundsun.com")
        QueryPayRequest in0);

}
